### PR TITLE
Adding support for multiple cookies

### PR DESCRIPTION
**Pull request by ShiroNexo**

### CODE REVIEW

**Comment by sglkc** [comment]
Its good, but using JSON in cookie will add more steps to the setup :thinking:

**Comment by ShiroNexo** [comment]
It support old and new one, for multile cookies you can use the json and single you can use like previous

**Comment by andiabrudan** [comment]
I tried doing the same, but realized it's too much code to change.
You can achieve the same thing with a smaller footprint by changing the workflow to use matrix strategy. This will basically just execute the same code again, but for another cookie.
Have a look at this commit. 4 lines change to achieve this.
github.com/andiabrudan/hoyolab-auto-daily/commit/59f0b424fbbb02047145e16ff88e9ec51a0611b6

**Comment by sglkc** [comment]
that's a better solution, thank you

**Pull request closed without merging**
